[build.environment]
HUGO_VERSION = "0.153.1"
NODE_VERSION = "25"
TZ = "America/Los_Angeles"

[build]
publish = "public"
command = "make all"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"
